apiVersion: apps/v1

kind: Deployment

metadata:

  name: reservation-service

spec:

  replicas: 2

  selector:

    matchLabels:

      app: reservation-service

  template:

    metadata:

      labels:

        app: reservation-service

    spec:

      containers:

      - name: reservation-service

        image: reservation-service:latest

        ports:

        - containerPort: 5003

        env:

        - name: DATABASE_HOST

          value: "postgres-service"

        - name: KAFKA_BOOTSTRAP_SERVERS

          value: "kafka-service:9092"

---

apiVersion: v1

kind: Service

metadata:

  name: reservation-service

spec:

  selector:

    app: reservation-service

  ports:

  - port: 5003

    targetPort: 5003

  type: ClusterIP 
